configVersion: 1
mysql:
  host: '127.0.0.1'
  port: '3306'
  username: root
  password: ''
  database: minecraft
loggedWorlds:
- world
logging:
  hiddenPlayers: []
queue:
  maxTimePerRun: 300
  timeBetweenRuns: 5
  minLogsToProcess: 25
  queueWarningSize: 1000
lookup:
  defaultDistance: 20
  defaultTime: 30 minutes
  linesPerPage: 15
tools:
  useCooldown: 3000
  itemtool:
    params: area 0 all sum none limit 5 extra desc
    itemId: 294
    itemData: 0
    leftClickBehavior: TOOL
    rightClickBehavior: BLOCK
  blocktool:
    params: area 0 all sum none limit 15 extra desc
    itemId: 7
    itemData: 0
    leftClickBehavior: TOOL
    rightClickBehavior: BLOCK
questioner:
  askRollbacks: true
  askRedos: true
  askClearlogs: true
event:
  callActionLogQueueEvent: false